/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tuwien_auto_calimero_serial_SerialComAdapter */

#ifndef _Included_tuwien_auto_calimero_serial_SerialComAdapter
#define _Included_tuwien_auto_calimero_serial_SerialComAdapter
#ifdef __cplusplus
extern "C" {
#endif
#undef tuwien_auto_calimero_serial_SerialComAdapter_BAUDRATE
#define tuwien_auto_calimero_serial_SerialComAdapter_BAUDRATE 1L
#undef tuwien_auto_calimero_serial_SerialComAdapter_PARITY
#define tuwien_auto_calimero_serial_SerialComAdapter_PARITY 2L
#undef tuwien_auto_calimero_serial_SerialComAdapter_DATABITS
#define tuwien_auto_calimero_serial_SerialComAdapter_DATABITS 3L
#undef tuwien_auto_calimero_serial_SerialComAdapter_STOPBITS
#define tuwien_auto_calimero_serial_SerialComAdapter_STOPBITS 4L
#undef tuwien_auto_calimero_serial_SerialComAdapter_FLOWCTRL
#define tuwien_auto_calimero_serial_SerialComAdapter_FLOWCTRL 5L
#undef tuwien_auto_calimero_serial_SerialComAdapter_FLOWCTRL_NONE
#define tuwien_auto_calimero_serial_SerialComAdapter_FLOWCTRL_NONE 0L
#undef tuwien_auto_calimero_serial_SerialComAdapter_FLOWCTRL_CTSRTS
#define tuwien_auto_calimero_serial_SerialComAdapter_FLOWCTRL_CTSRTS 1L
#undef tuwien_auto_calimero_serial_SerialComAdapter_PARITY_NONE
#define tuwien_auto_calimero_serial_SerialComAdapter_PARITY_NONE 0L
#undef tuwien_auto_calimero_serial_SerialComAdapter_PARITY_ODD
#define tuwien_auto_calimero_serial_SerialComAdapter_PARITY_ODD 1L
#undef tuwien_auto_calimero_serial_SerialComAdapter_PARITY_EVEN
#define tuwien_auto_calimero_serial_SerialComAdapter_PARITY_EVEN 2L
#undef tuwien_auto_calimero_serial_SerialComAdapter_PARITY_MARK
#define tuwien_auto_calimero_serial_SerialComAdapter_PARITY_MARK 3L
#undef tuwien_auto_calimero_serial_SerialComAdapter_ONE_STOPBIT
#define tuwien_auto_calimero_serial_SerialComAdapter_ONE_STOPBIT 1L
#undef tuwien_auto_calimero_serial_SerialComAdapter_TWO_STOPBITS
#define tuwien_auto_calimero_serial_SerialComAdapter_TWO_STOPBITS 2L
#undef tuwien_auto_calimero_serial_SerialComAdapter_AVAILABLE_INPUT_STATUS
#define tuwien_auto_calimero_serial_SerialComAdapter_AVAILABLE_INPUT_STATUS 2L
#undef tuwien_auto_calimero_serial_SerialComAdapter_ERROR_STATUS
#define tuwien_auto_calimero_serial_SerialComAdapter_ERROR_STATUS 1L
#undef tuwien_auto_calimero_serial_SerialComAdapter_LINE_STATUS
#define tuwien_auto_calimero_serial_SerialComAdapter_LINE_STATUS 3L
#undef tuwien_auto_calimero_serial_SerialComAdapter_EVENT_RXCHAR
#define tuwien_auto_calimero_serial_SerialComAdapter_EVENT_RXCHAR 1L
#undef tuwien_auto_calimero_serial_SerialComAdapter_EVENT_RXFLAG
#define tuwien_auto_calimero_serial_SerialComAdapter_EVENT_RXFLAG 2L
#undef tuwien_auto_calimero_serial_SerialComAdapter_EVENT_TXEMPTY
#define tuwien_auto_calimero_serial_SerialComAdapter_EVENT_TXEMPTY 4L
#undef tuwien_auto_calimero_serial_SerialComAdapter_EVENT_CTS
#define tuwien_auto_calimero_serial_SerialComAdapter_EVENT_CTS 8L
#undef tuwien_auto_calimero_serial_SerialComAdapter_EVENT_DSR
#define tuwien_auto_calimero_serial_SerialComAdapter_EVENT_DSR 16L
#undef tuwien_auto_calimero_serial_SerialComAdapter_EVENT_RLSD
#define tuwien_auto_calimero_serial_SerialComAdapter_EVENT_RLSD 32L
#undef tuwien_auto_calimero_serial_SerialComAdapter_EVENT_BREAK
#define tuwien_auto_calimero_serial_SerialComAdapter_EVENT_BREAK 64L
#undef tuwien_auto_calimero_serial_SerialComAdapter_EVENT_ERR
#define tuwien_auto_calimero_serial_SerialComAdapter_EVENT_ERR 128L
#undef tuwien_auto_calimero_serial_SerialComAdapter_EVENT_RING
#define tuwien_auto_calimero_serial_SerialComAdapter_EVENT_RING 256L
#undef tuwien_auto_calimero_serial_SerialComAdapter_INVALID_HANDLE
#define tuwien_auto_calimero_serial_SerialComAdapter_INVALID_HANDLE -1L
/*
 * Class:     tuwien_auto_calimero_serial_SerialComAdapter
 * Method:    portExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_tuwien_auto_calimero_serial_SerialComAdapter_portExists
  (JNIEnv *, jclass, jstring);

/*
 * Class:     tuwien_auto_calimero_serial_SerialComAdapter
 * Method:    writeBytes
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_tuwien_auto_calimero_serial_SerialComAdapter_writeBytes
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     tuwien_auto_calimero_serial_SerialComAdapter
 * Method:    write
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_tuwien_auto_calimero_serial_SerialComAdapter_write
  (JNIEnv *, jobject, jint);

/*
 * Class:     tuwien_auto_calimero_serial_SerialComAdapter
 * Method:    readBytes
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_tuwien_auto_calimero_serial_SerialComAdapter_readBytes
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     tuwien_auto_calimero_serial_SerialComAdapter
 * Method:    read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tuwien_auto_calimero_serial_SerialComAdapter_read
  (JNIEnv *, jobject);

/*
 * Class:     tuwien_auto_calimero_serial_SerialComAdapter
 * Method:    setTimeouts
 * Signature: (Ltuwien/auto/calimero/serial/SerialComAdapter/Timeouts;)V
 */
JNIEXPORT void JNICALL Java_tuwien_auto_calimero_serial_SerialComAdapter_setTimeouts
  (JNIEnv *, jobject, jobject);

/*
 * Class:     tuwien_auto_calimero_serial_SerialComAdapter
 * Method:    getTimeouts
 * Signature: ()Ltuwien/auto/calimero/serial/SerialComAdapter/Timeouts;
 */
JNIEXPORT jobject JNICALL Java_tuwien_auto_calimero_serial_SerialComAdapter_getTimeouts
  (JNIEnv *, jobject);

/*
 * Class:     tuwien_auto_calimero_serial_SerialComAdapter
 * Method:    getStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_tuwien_auto_calimero_serial_SerialComAdapter_getStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     tuwien_auto_calimero_serial_SerialComAdapter
 * Method:    setControl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_tuwien_auto_calimero_serial_SerialComAdapter_setControl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     tuwien_auto_calimero_serial_SerialComAdapter
 * Method:    getControl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_tuwien_auto_calimero_serial_SerialComAdapter_getControl
  (JNIEnv *, jobject, jint);

/*
 * Class:     tuwien_auto_calimero_serial_SerialComAdapter
 * Method:    setEvents
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_tuwien_auto_calimero_serial_SerialComAdapter_setEvents
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     tuwien_auto_calimero_serial_SerialComAdapter
 * Method:    waitEvent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tuwien_auto_calimero_serial_SerialComAdapter_waitEvent
  (JNIEnv *, jobject);

/*
 * Class:     tuwien_auto_calimero_serial_SerialComAdapter
 * Method:    open
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tuwien_auto_calimero_serial_SerialComAdapter_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tuwien_auto_calimero_serial_SerialComAdapter
 * Method:    close0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tuwien_auto_calimero_serial_SerialComAdapter_close0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class tuwien_auto_calimero_serial_SerialComAdapter_Timeouts */

#ifndef _Included_tuwien_auto_calimero_serial_SerialComAdapter_Timeouts
#define _Included_tuwien_auto_calimero_serial_SerialComAdapter_Timeouts
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
