/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_calimero_serial_provider_jni_TtySerialCom */

#ifndef _Included_io_calimero_serial_provider_jni_TtySerialCom
#define _Included_io_calimero_serial_provider_jni_TtySerialCom
#ifdef __cplusplus
extern "C" {
#endif
#undef io_calimero_serial_provider_jni_TtySerialCom_BAUDRATE
#define io_calimero_serial_provider_jni_TtySerialCom_BAUDRATE 1L
#undef io_calimero_serial_provider_jni_TtySerialCom_PARITY
#define io_calimero_serial_provider_jni_TtySerialCom_PARITY 2L
#undef io_calimero_serial_provider_jni_TtySerialCom_DATABITS
#define io_calimero_serial_provider_jni_TtySerialCom_DATABITS 3L
#undef io_calimero_serial_provider_jni_TtySerialCom_STOPBITS
#define io_calimero_serial_provider_jni_TtySerialCom_STOPBITS 4L
#undef io_calimero_serial_provider_jni_TtySerialCom_FLOWCTRL
#define io_calimero_serial_provider_jni_TtySerialCom_FLOWCTRL 5L
#undef io_calimero_serial_provider_jni_TtySerialCom_FLOWCTRL_NONE
#define io_calimero_serial_provider_jni_TtySerialCom_FLOWCTRL_NONE 0L
#undef io_calimero_serial_provider_jni_TtySerialCom_FLOWCTRL_CTSRTS
#define io_calimero_serial_provider_jni_TtySerialCom_FLOWCTRL_CTSRTS 1L
#undef io_calimero_serial_provider_jni_TtySerialCom_PARITY_NONE
#define io_calimero_serial_provider_jni_TtySerialCom_PARITY_NONE 0L
#undef io_calimero_serial_provider_jni_TtySerialCom_PARITY_ODD
#define io_calimero_serial_provider_jni_TtySerialCom_PARITY_ODD 1L
#undef io_calimero_serial_provider_jni_TtySerialCom_PARITY_EVEN
#define io_calimero_serial_provider_jni_TtySerialCom_PARITY_EVEN 2L
#undef io_calimero_serial_provider_jni_TtySerialCom_PARITY_MARK
#define io_calimero_serial_provider_jni_TtySerialCom_PARITY_MARK 3L
#undef io_calimero_serial_provider_jni_TtySerialCom_ONE_STOPBIT
#define io_calimero_serial_provider_jni_TtySerialCom_ONE_STOPBIT 1L
#undef io_calimero_serial_provider_jni_TtySerialCom_TWO_STOPBITS
#define io_calimero_serial_provider_jni_TtySerialCom_TWO_STOPBITS 2L
#undef io_calimero_serial_provider_jni_TtySerialCom_AVAILABLE_INPUT_STATUS
#define io_calimero_serial_provider_jni_TtySerialCom_AVAILABLE_INPUT_STATUS 2L
#undef io_calimero_serial_provider_jni_TtySerialCom_ERROR_STATUS
#define io_calimero_serial_provider_jni_TtySerialCom_ERROR_STATUS 1L
#undef io_calimero_serial_provider_jni_TtySerialCom_LINE_STATUS
#define io_calimero_serial_provider_jni_TtySerialCom_LINE_STATUS 3L
#undef io_calimero_serial_provider_jni_TtySerialCom_EVENT_RXCHAR
#define io_calimero_serial_provider_jni_TtySerialCom_EVENT_RXCHAR 1L
#undef io_calimero_serial_provider_jni_TtySerialCom_EVENT_RXFLAG
#define io_calimero_serial_provider_jni_TtySerialCom_EVENT_RXFLAG 2L
#undef io_calimero_serial_provider_jni_TtySerialCom_EVENT_TXEMPTY
#define io_calimero_serial_provider_jni_TtySerialCom_EVENT_TXEMPTY 4L
#undef io_calimero_serial_provider_jni_TtySerialCom_EVENT_CTS
#define io_calimero_serial_provider_jni_TtySerialCom_EVENT_CTS 8L
#undef io_calimero_serial_provider_jni_TtySerialCom_EVENT_DSR
#define io_calimero_serial_provider_jni_TtySerialCom_EVENT_DSR 16L
#undef io_calimero_serial_provider_jni_TtySerialCom_EVENT_RLSD
#define io_calimero_serial_provider_jni_TtySerialCom_EVENT_RLSD 32L
#undef io_calimero_serial_provider_jni_TtySerialCom_EVENT_BREAK
#define io_calimero_serial_provider_jni_TtySerialCom_EVENT_BREAK 64L
#undef io_calimero_serial_provider_jni_TtySerialCom_EVENT_ERR
#define io_calimero_serial_provider_jni_TtySerialCom_EVENT_ERR 128L
#undef io_calimero_serial_provider_jni_TtySerialCom_EVENT_RING
#define io_calimero_serial_provider_jni_TtySerialCom_EVENT_RING 256L
#undef io_calimero_serial_provider_jni_TtySerialCom_INVALID_HANDLE
#define io_calimero_serial_provider_jni_TtySerialCom_INVALID_HANDLE -1L
/*
 * Class:     io_calimero_serial_provider_jni_TtySerialCom
 * Method:    portExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_calimero_serial_provider_jni_TtySerialCom_portExists
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_calimero_serial_provider_jni_TtySerialCom
 * Method:    writeBytes
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_io_calimero_serial_provider_jni_TtySerialCom_writeBytes
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     io_calimero_serial_provider_jni_TtySerialCom
 * Method:    write
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_calimero_serial_provider_jni_TtySerialCom_write
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_calimero_serial_provider_jni_TtySerialCom
 * Method:    readBytes
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_io_calimero_serial_provider_jni_TtySerialCom_readBytes
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     io_calimero_serial_provider_jni_TtySerialCom
 * Method:    read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_calimero_serial_provider_jni_TtySerialCom_read
  (JNIEnv *, jobject);

/*
 * Class:     io_calimero_serial_provider_jni_TtySerialCom
 * Method:    setTimeouts
 * Signature: (Lio/calimero/serial/provider/jni/TtySerialCom/Timeouts;)V
 */
JNIEXPORT void JNICALL Java_io_calimero_serial_provider_jni_TtySerialCom_setTimeouts
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_calimero_serial_provider_jni_TtySerialCom
 * Method:    getTimeouts
 * Signature: ()Lio/calimero/serial/provider/jni/TtySerialCom/Timeouts;
 */
JNIEXPORT jobject JNICALL Java_io_calimero_serial_provider_jni_TtySerialCom_getTimeouts
  (JNIEnv *, jobject);

/*
 * Class:     io_calimero_serial_provider_jni_TtySerialCom
 * Method:    getStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_calimero_serial_provider_jni_TtySerialCom_getStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_calimero_serial_provider_jni_TtySerialCom
 * Method:    setControl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_io_calimero_serial_provider_jni_TtySerialCom_setControl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_calimero_serial_provider_jni_TtySerialCom
 * Method:    getControl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_calimero_serial_provider_jni_TtySerialCom_getControl
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_calimero_serial_provider_jni_TtySerialCom
 * Method:    setEvents
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_io_calimero_serial_provider_jni_TtySerialCom_setEvents
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     io_calimero_serial_provider_jni_TtySerialCom
 * Method:    waitEvent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_calimero_serial_provider_jni_TtySerialCom_waitEvent
  (JNIEnv *, jobject);

/*
 * Class:     io_calimero_serial_provider_jni_TtySerialCom
 * Method:    open
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_calimero_serial_provider_jni_TtySerialCom_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_calimero_serial_provider_jni_TtySerialCom
 * Method:    close0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_calimero_serial_provider_jni_TtySerialCom_close0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
